name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Semantic Version
        id: versioning
        run: echo "VERSION=$(git describe --tags --always --match 'v*' || echo 'v0.1.0')" >> $GITHUB_ENV

      - name: Update Version in pom.xml (Maven)
        run: | 
          mvn versions:set -DnewVersion=${{ env.VERSION }}
          mvn versions:commit

      - name: Commit Updated pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add pom.xml
          git commit -m "Update pom.xml version to ${{ env.VERSION }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

      - name: Verify Updated Version
        run: cat pom.xml | grep "<version>"

      - name: Build the Application
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app-jar
          path: target/Springboot-Application-*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-app-jar
          path: target/

      - name: Build Docker Image
        run: |
          docker build -t my-springboot-app:${{ env.VERSION }} .
          docker tag my-springboot-app:${{ env.VERSION }} my-dockerhub-user/my-springboot-app:${{ env.VERSION }}

      - name: Push Docker Image
        run: |
          docker push my-dockerhub-user/my-springboot-app:${{ env.VERSION }}

