name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
     
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Semantic Version
        id: versioning
        run: echo "VERSION=$(git describe --tags --always --match 'v*' || echo 'v0.1.0')" >> $GITHUB_ENV

      - name: Update Version in pom.xml (Maven)
  	run: | 
    	  mvn versions:set -DnewVersion=${{ env.VERSION }}
    	  mvn versions:commit

      - name: Verify Updated Version
        run: cat pom.xml | grep "<version>"


